/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiScenarioRouteImport } from './routes/api/scenario'
import { Route as ApiCommentaryRouteImport } from './routes/api/commentary'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScenarioRoute = ApiScenarioRouteImport.update({
  id: '/api/scenario',
  path: '/api/scenario',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommentaryRoute = ApiCommentaryRouteImport.update({
  id: '/api/commentary',
  path: '/api/commentary',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/commentary': typeof ApiCommentaryRoute
  '/api/scenario': typeof ApiScenarioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/commentary': typeof ApiCommentaryRoute
  '/api/scenario': typeof ApiScenarioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/commentary': typeof ApiCommentaryRoute
  '/api/scenario': typeof ApiScenarioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sitemap.xml' | '/api/commentary' | '/api/scenario'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sitemap.xml' | '/api/commentary' | '/api/scenario'
  id: '__root__' | '/' | '/sitemap.xml' | '/api/commentary' | '/api/scenario'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiCommentaryRoute: typeof ApiCommentaryRoute
  ApiScenarioRoute: typeof ApiScenarioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scenario': {
      id: '/api/scenario'
      path: '/api/scenario'
      fullPath: '/api/scenario'
      preLoaderRoute: typeof ApiScenarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/commentary': {
      id: '/api/commentary'
      path: '/api/commentary'
      fullPath: '/api/commentary'
      preLoaderRoute: typeof ApiCommentaryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiCommentaryRoute: ApiCommentaryRoute,
  ApiScenarioRoute: ApiScenarioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
